[package]
name = "esp32-conways-game-of-life-rs"
version = "0.2.0"
authors = ["Juraj Michálek <juraj.michalek@espressif.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal = { package = "esp32s3-hal", version = "0.13.0" }
esp-backtrace = { version = "0.9.0", features = ["esp32s3", "panic-handler", "exception-handler", "print-uart"] }
esp-println = { version = "0.7.0", features = ["esp32s3","log"] }
log = { version = "0.4.18" }
mipidsi = "0.7.1"
embedded-graphics = "0.8.1"
embedded-graphics-framebuf = { version = "0.3.0", git = "https://github.com/georgik/embedded-graphics-framebuf.git", branch = "feature/embedded-graphics-0.8" }
display-interface = "0.4.1"
display-interface-spi = "0.4.1"
heapless = "0.8.0"
embedded-dma = "0.2.0"
spi-dma-displayinterface = { git = "https://github.com/georgik/esp32-spooky-maze-game.git", package = "spi-dma-displayinterface", features = [ "esp32s3" ] }
