# This is a workspace root for the xtask runner only
[workspace]
members = [
    "xtask",
]
exclude = [
    "esope-*",
    "esp32-*", 
    "m5stack-*",
    "waveshare-*",
    "update-deps",
]
resolver = "2"
