[wokwi]
version = 1

elf = "target/xtensa-esp32s3-none-elf/release/esp32-conways-game-of-life-rs"
firmware = "target/xtensa-esp32s3-none-elf/release/esp32-conways-game-of-life-rs"

gdbServerPort = 3333
#elf = "target/xtensa-esp32s3-none-elf/debug/esp32-conways-game-of-life-rs"
#firmware = "target/xtensa-esp32s3-none-elf/debug/esp32-conways-game-of-life-rs"


