[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[env]
ESP_LOG="INFO"
# ESP_HAL_CONFIG_PSRAM_MODE = "octal"

[build]
rustflags = [
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
