[package]
edition = "2024"
name    = "esp32-conways-game-of-life-rs"
version = "0.7.0"

[[bin]]
name = "esp32-conways-game-of-life-rs"
path = "./src/bin/main.rs"

[dependencies]
esp-alloc = "0.8.0"
esp-backtrace = { version = "0.17.0", features = ["esp32s3", "panic-handler", "println"] }
esp-hal = { version = "1.0.0-beta.1", features = ["esp32s3", "psram", "unstable"] }
esp-println = { version = "0.15.0", features = ["auto", "log-04"] }
log = "0.4.27"

embedded-graphics = "0.8.1"
embedded-graphics-framebuf = "0.5.0"
embassy-executor    = { version = "0.7.0", features = ["task-arena-size-20480"] }
embassy-sync        = "0.7.0"
embassy-time        = "0.4.0"
esp-hal-embassy = { version = "0.9.0", features = ["esp32s3"] }
static_cell         = { version = "2.1.0", features = ["nightly"] }
heapless = "0.8.0"
sh8601-rs = { version = "0.1.4", features = ["waveshare_18_amoled"] }
embedded-hal-bus = "0.3.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
