name: CI RISC-V IMAC

on:
  push:
    paths:
      - "esp32-c6-waveshare-1_47/**"
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the GitHub Release'
        required: true
        default: 'v0.5.0'
      release_tag:
        description: 'Tag for the GitHub Release'
        required: true
        default: 'v0.5.0'
      prefix:
        description: 'Prefix for binary name'
        required: true
        default: 'esp32-conways-game-of-life'
      board:
        description: 'Target directory for the ESP32-C6 project (e.g. esp32-c6-waveshare-1_47)'
        required: true
        default: 'esp32-c6-waveshare-1_47'

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  riscv-imc-release:
    name: RISC-V IMAC CI (ESP32-C6 Projects)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust for RISC-V IMAC
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: riscv32imac-unknown-none-elf

      - name: Build ESP32-C6 Project and Collect Assets
        run: |
          cd "${{ github.event.inputs.board }}"
          cargo build --release
          cargo fmt --all -- --check --color always
          cargo clippy --all-features --workspace -- -D warnings
