name: CI RISC-V IMC

on:
  push:
    paths:
      - "esp32-c3-lcdkit/**"
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the GitHub Release'
        required: true
        default: 'v0.5.0'
      release_tag:
        description: 'Tag for the GitHub Release'
        required: true
        default: 'v0.5.0'
      prefix:
        description: 'Prefix for binary name'
        required: true
        default: 'esp32-conways-game-of-life'

env:
    CARGO_TERM_COLOR: always
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  riscv-imc-release:
    name: RISC-V IMC CI (ESP32-C3 Projects)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust for RISC-V IMC
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: riscv32imc-unknown-none-elf

      - name: Build ESP32-C3 Project and Collect Assets
        run: |
          cd "esp32-c3-lcdkit"
          cargo build --release
          cargo fmt --all -- --check --color always
          cargo clippy --all-features --workspace -- -D warnings
