name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build ESP32 Projects
        run: |
          for dir in esp32-c3-lcdkit esp32-c6-waveshare-1_47 esp32-s3-box-3 esp32-s3-box-3-minimal; do
            cd $dir && cargo build --release && cd ..
          done

      - name: Build WASM Package
        run: |
          cd wasm
          wasm-pack build --target web --release

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload WASM Assets to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wasm/pkg/*.wasm
            wasm/pkg/*.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy WASM to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: wasm/pkg
          token: ${{ secrets.GITHUB_TOKEN }}
